remote_theme: coursweb/jk-theme

title: Titre exemple

description: Description de cet exemple

lang: fr-FR

robots: noindex, nofollow

# menu 
chapters:
 - title: Cours-Web
   url: https://cours-web.ch/
 - title: MDN
   url: https://developer.mozilla.org/fr/

# pied de page   
footer_col_1: <ul class="contact-list">
  <li>Eracom, Lausanne</li>
  <li>2022</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/">Lien Github</a></li></ul>
