title: null
show_githublink: false
repository: 
description: 

markdown: GFM

plugins:
  - jekyll-gfm-admonitions
  - jekyll-optional-front-matter

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - node_modules/
  - .sass-cache/
  - .jekyll-cache/
